---
# handlers file for nfs

- name: "NFS: Restart"
  become: true
  ansible.builtin.service:
    name: "{{ item }}"
    state: restarted
  loop:
    - "{{ nfs_service_name }}"
  when:
    - nfs_package_state != 'absent'
