---
- name: Converge
  hosts: all
  gather_facts: true
  pre_tasks:
    - name: Update apt cache.
      ansible.builtin.apt:
        update_cache: true
      when: ansible_os_family == 'Debian'

    - name: Update dnf cache.
      ansible.builtin.dnf:
        update_cache: true
      when: ansible_os_family == 'RedHat'

    - name: Install dependencies (RedHat).
      ansible.builtin.package:
        name:
          - python3-pip
        state: present
      when: ansible_os_family == 'RedHat'

    - name: Install dependencies (Debian).
      ansible.builtin.apt:
        name:
          - python3-pip
        state: present
      when: ansible_os_family == 'Debian'

  roles:
    - giftpilz0.server.cockpit
    - giftpilz0.server.httpd
    - giftpilz0.server.mariadb
    - giftpilz0.server.nfs
    - giftpilz0.server.pcp
    - giftpilz0.server.podman
