---
# tasks file for httpd

######################################
### packages

- name: "Httpd: Manage dependencies"
  become: true
  ansible.builtin.package:
    name: "{{ httpd_package }}"
    state: "{{ httpd_package_state }}"

######################################
### services

- name: "Httpd: Manage services"
  become: true
  ansible.builtin.systemd:
    name: "{{ httpd_service_name }}"
    state: "{{ httpd_service_state }}"
    enabled: "{{ httpd_service_enabled }}"
  when:
    - httpd_package_state != 'absent'
