---
name: Ansible lint

# yamllint disable-line rule:truthy
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  ansible-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          pip install ansible ansible-lint

      - name: Lint playbook
        run: |
          ansible-lint
